package com.joycity.joyclub.apifront.modal.cart;

import java.util.Date;

public class ClientPostAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.client_id
     *
     * @mbg.generated
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.last_use_time
     *
     * @mbg.generated
     */
    private Date lastUseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_post_address.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.id
     *
     * @return the value of client_post_address.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.id
     *
     * @param id the value for client_post_address.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.client_id
     *
     * @return the value of client_post_address.client_id
     *
     * @mbg.generated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.client_id
     *
     * @param clientId the value for client_post_address.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.name
     *
     * @return the value of client_post_address.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.name
     *
     * @param name the value for client_post_address.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.phone
     *
     * @return the value of client_post_address.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.phone
     *
     * @param phone the value for client_post_address.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.address
     *
     * @return the value of client_post_address.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.address
     *
     * @param address the value for client_post_address.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.postcode
     *
     * @return the value of client_post_address.postcode
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.postcode
     *
     * @param postcode the value for client_post_address.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.last_use_time
     *
     * @return the value of client_post_address.last_use_time
     *
     * @mbg.generated
     */
    public Date getLastUseTime() {
        return lastUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.last_use_time
     *
     * @param lastUseTime the value for client_post_address.last_use_time
     *
     * @mbg.generated
     */
    public void setLastUseTime(Date lastUseTime) {
        this.lastUseTime = lastUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.create_time
     *
     * @return the value of client_post_address.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.create_time
     *
     * @param createTime the value for client_post_address.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.last_update
     *
     * @return the value of client_post_address.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.last_update
     *
     * @param lastUpdate the value for client_post_address.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.delete_flag
     *
     * @return the value of client_post_address.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.delete_flag
     *
     * @param deleteFlag the value for client_post_address.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_post_address.delete_time
     *
     * @return the value of client_post_address.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_post_address.delete_time
     *
     * @param deleteTime the value for client_post_address.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}