package com.joycity.joyclub.apifront.modal.designer;

import java.util.Date;

public class Designer {
    private String htmlContent;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.store_id
     *
     * @mbg.generated
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.head_img
     *
     * @mbg.generated
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.portrait
     *
     * @mbg.generated
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_store_designer.delate_time
     *
     * @mbg.generated
     */
    private Date delateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.id
     *
     * @return the value of sale_store_designer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.id
     *
     * @param id the value for sale_store_designer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.store_id
     *
     * @return the value of sale_store_designer.store_id
     *
     * @mbg.generated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.store_id
     *
     * @param storeId the value for sale_store_designer.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.head_img
     *
     * @return the value of sale_store_designer.head_img
     *
     * @mbg.generated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.head_img
     *
     * @param headImg the value for sale_store_designer.head_img
     *
     * @mbg.generated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.portrait
     *
     * @return the value of sale_store_designer.portrait
     *
     * @mbg.generated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.portrait
     *
     * @param portrait the value for sale_store_designer.portrait
     *
     * @mbg.generated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.name
     *
     * @return the value of sale_store_designer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.name
     *
     * @param name the value for sale_store_designer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.intro
     *
     * @return the value of sale_store_designer.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.intro
     *
     * @param intro the value for sale_store_designer.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.create_time
     *
     * @return the value of sale_store_designer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.create_time
     *
     * @param createTime the value for sale_store_designer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.last_update
     *
     * @return the value of sale_store_designer.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.last_update
     *
     * @param lastUpdate the value for sale_store_designer.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.delete_flag
     *
     * @return the value of sale_store_designer.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.delete_flag
     *
     * @param deleteFlag the value for sale_store_designer.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_store_designer.delate_time
     *
     * @return the value of sale_store_designer.delate_time
     *
     * @mbg.generated
     */
    public Date getDelateTime() {
        return delateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_store_designer.delate_time
     *
     * @param delateTime the value for sale_store_designer.delate_time
     *
     * @mbg.generated
     */
    public void setDelateTime(Date delateTime) {
        this.delateTime = delateTime;
    }

    public String getHtmlContent() {
        return htmlContent;
    }

    public void setHtmlContent(String htmlContent) {
        this.htmlContent = htmlContent;
    }

}