package com.joycity.joyclub.apifront.modal.client;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public ClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Long value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Long value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Long value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Long value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Long value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Long value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Long> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Long> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Long value1, Long value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Long value1, Long value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andVipGradeIsNull() {
            addCriterion("vip_grade is null");
            return (Criteria) this;
        }

        public Criteria andVipGradeIsNotNull() {
            addCriterion("vip_grade is not null");
            return (Criteria) this;
        }

        public Criteria andVipGradeEqualTo(Integer value) {
            addCriterion("vip_grade =", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotEqualTo(Integer value) {
            addCriterion("vip_grade <>", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeGreaterThan(Integer value) {
            addCriterion("vip_grade >", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip_grade >=", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeLessThan(Integer value) {
            addCriterion("vip_grade <", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeLessThanOrEqualTo(Integer value) {
            addCriterion("vip_grade <=", value, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeIn(List<Integer> values) {
            addCriterion("vip_grade in", values, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotIn(List<Integer> values) {
            addCriterion("vip_grade not in", values, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeBetween(Integer value1, Integer value2) {
            addCriterion("vip_grade between", value1, value2, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("vip_grade not between", value1, value2, "vipGrade");
            return (Criteria) this;
        }

        public Criteria andVipPointIsNull() {
            addCriterion("vip_point is null");
            return (Criteria) this;
        }

        public Criteria andVipPointIsNotNull() {
            addCriterion("vip_point is not null");
            return (Criteria) this;
        }

        public Criteria andVipPointEqualTo(Integer value) {
            addCriterion("vip_point =", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointNotEqualTo(Integer value) {
            addCriterion("vip_point <>", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointGreaterThan(Integer value) {
            addCriterion("vip_point >", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip_point >=", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointLessThan(Integer value) {
            addCriterion("vip_point <", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointLessThanOrEqualTo(Integer value) {
            addCriterion("vip_point <=", value, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointIn(List<Integer> values) {
            addCriterion("vip_point in", values, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointNotIn(List<Integer> values) {
            addCriterion("vip_point not in", values, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointBetween(Integer value1, Integer value2) {
            addCriterion("vip_point between", value1, value2, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andVipPointNotBetween(Integer value1, Integer value2) {
            addCriterion("vip_point not between", value1, value2, "vipPoint");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andVipCodeIsNull() {
            addCriterion("vip_code is null");
            return (Criteria) this;
        }

        public Criteria andVipCodeIsNotNull() {
            addCriterion("vip_code is not null");
            return (Criteria) this;
        }

        public Criteria andVipCodeEqualTo(String value) {
            addCriterion("vip_code =", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotEqualTo(String value) {
            addCriterion("vip_code <>", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeGreaterThan(String value) {
            addCriterion("vip_code >", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vip_code >=", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLessThan(String value) {
            addCriterion("vip_code <", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLessThanOrEqualTo(String value) {
            addCriterion("vip_code <=", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLike(String value) {
            addCriterion("vip_code like", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotLike(String value) {
            addCriterion("vip_code not like", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeIn(List<String> values) {
            addCriterion("vip_code in", values, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotIn(List<String> values) {
            addCriterion("vip_code not in", values, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeBetween(String value1, String value2) {
            addCriterion("vip_code between", value1, value2, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotBetween(String value1, String value2) {
            addCriterion("vip_code not between", value1, value2, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeIsNull() {
            addCriterion("vip_card_grade is null");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeIsNotNull() {
            addCriterion("vip_card_grade is not null");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeEqualTo(String value) {
            addCriterion("vip_card_grade =", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeNotEqualTo(String value) {
            addCriterion("vip_card_grade <>", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeGreaterThan(String value) {
            addCriterion("vip_card_grade >", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeGreaterThanOrEqualTo(String value) {
            addCriterion("vip_card_grade >=", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeLessThan(String value) {
            addCriterion("vip_card_grade <", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeLessThanOrEqualTo(String value) {
            addCriterion("vip_card_grade <=", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeLike(String value) {
            addCriterion("vip_card_grade like", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeNotLike(String value) {
            addCriterion("vip_card_grade not like", value, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeIn(List<String> values) {
            addCriterion("vip_card_grade in", values, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeNotIn(List<String> values) {
            addCriterion("vip_card_grade not in", values, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeBetween(String value1, String value2) {
            addCriterion("vip_card_grade between", value1, value2, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andVipCardGradeNotBetween(String value1, String value2) {
            addCriterion("vip_card_grade not between", value1, value2, "vipCardGrade");
            return (Criteria) this;
        }

        public Criteria andEduHisIsNull() {
            addCriterion("edu_his is null");
            return (Criteria) this;
        }

        public Criteria andEduHisIsNotNull() {
            addCriterion("edu_his is not null");
            return (Criteria) this;
        }

        public Criteria andEduHisEqualTo(String value) {
            addCriterion("edu_his =", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisNotEqualTo(String value) {
            addCriterion("edu_his <>", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisGreaterThan(String value) {
            addCriterion("edu_his >", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisGreaterThanOrEqualTo(String value) {
            addCriterion("edu_his >=", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisLessThan(String value) {
            addCriterion("edu_his <", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisLessThanOrEqualTo(String value) {
            addCriterion("edu_his <=", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisLike(String value) {
            addCriterion("edu_his like", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisNotLike(String value) {
            addCriterion("edu_his not like", value, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisIn(List<String> values) {
            addCriterion("edu_his in", values, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisNotIn(List<String> values) {
            addCriterion("edu_his not in", values, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisBetween(String value1, String value2) {
            addCriterion("edu_his between", value1, value2, "eduHis");
            return (Criteria) this;
        }

        public Criteria andEduHisNotBetween(String value1, String value2) {
            addCriterion("edu_his not between", value1, value2, "eduHis");
            return (Criteria) this;
        }

        public Criteria andWxCityIsNull() {
            addCriterion("wx_city is null");
            return (Criteria) this;
        }

        public Criteria andWxCityIsNotNull() {
            addCriterion("wx_city is not null");
            return (Criteria) this;
        }

        public Criteria andWxCityEqualTo(String value) {
            addCriterion("wx_city =", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityNotEqualTo(String value) {
            addCriterion("wx_city <>", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityGreaterThan(String value) {
            addCriterion("wx_city >", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityGreaterThanOrEqualTo(String value) {
            addCriterion("wx_city >=", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityLessThan(String value) {
            addCriterion("wx_city <", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityLessThanOrEqualTo(String value) {
            addCriterion("wx_city <=", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityLike(String value) {
            addCriterion("wx_city like", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityNotLike(String value) {
            addCriterion("wx_city not like", value, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityIn(List<String> values) {
            addCriterion("wx_city in", values, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityNotIn(List<String> values) {
            addCriterion("wx_city not in", values, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityBetween(String value1, String value2) {
            addCriterion("wx_city between", value1, value2, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCityNotBetween(String value1, String value2) {
            addCriterion("wx_city not between", value1, value2, "wxCity");
            return (Criteria) this;
        }

        public Criteria andWxCountryIsNull() {
            addCriterion("wx_country is null");
            return (Criteria) this;
        }

        public Criteria andWxCountryIsNotNull() {
            addCriterion("wx_country is not null");
            return (Criteria) this;
        }

        public Criteria andWxCountryEqualTo(String value) {
            addCriterion("wx_country =", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryNotEqualTo(String value) {
            addCriterion("wx_country <>", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryGreaterThan(String value) {
            addCriterion("wx_country >", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryGreaterThanOrEqualTo(String value) {
            addCriterion("wx_country >=", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryLessThan(String value) {
            addCriterion("wx_country <", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryLessThanOrEqualTo(String value) {
            addCriterion("wx_country <=", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryLike(String value) {
            addCriterion("wx_country like", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryNotLike(String value) {
            addCriterion("wx_country not like", value, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryIn(List<String> values) {
            addCriterion("wx_country in", values, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryNotIn(List<String> values) {
            addCriterion("wx_country not in", values, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryBetween(String value1, String value2) {
            addCriterion("wx_country between", value1, value2, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxCountryNotBetween(String value1, String value2) {
            addCriterion("wx_country not between", value1, value2, "wxCountry");
            return (Criteria) this;
        }

        public Criteria andWxGenderIsNull() {
            addCriterion("wx_gender is null");
            return (Criteria) this;
        }

        public Criteria andWxGenderIsNotNull() {
            addCriterion("wx_gender is not null");
            return (Criteria) this;
        }

        public Criteria andWxGenderEqualTo(String value) {
            addCriterion("wx_gender =", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderNotEqualTo(String value) {
            addCriterion("wx_gender <>", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderGreaterThan(String value) {
            addCriterion("wx_gender >", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderGreaterThanOrEqualTo(String value) {
            addCriterion("wx_gender >=", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderLessThan(String value) {
            addCriterion("wx_gender <", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderLessThanOrEqualTo(String value) {
            addCriterion("wx_gender <=", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderLike(String value) {
            addCriterion("wx_gender like", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderNotLike(String value) {
            addCriterion("wx_gender not like", value, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderIn(List<String> values) {
            addCriterion("wx_gender in", values, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderNotIn(List<String> values) {
            addCriterion("wx_gender not in", values, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderBetween(String value1, String value2) {
            addCriterion("wx_gender between", value1, value2, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxGenderNotBetween(String value1, String value2) {
            addCriterion("wx_gender not between", value1, value2, "wxGender");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlIsNull() {
            addCriterion("wx_head_img_url is null");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlIsNotNull() {
            addCriterion("wx_head_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlEqualTo(String value) {
            addCriterion("wx_head_img_url =", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlNotEqualTo(String value) {
            addCriterion("wx_head_img_url <>", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlGreaterThan(String value) {
            addCriterion("wx_head_img_url >", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("wx_head_img_url >=", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlLessThan(String value) {
            addCriterion("wx_head_img_url <", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlLessThanOrEqualTo(String value) {
            addCriterion("wx_head_img_url <=", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlLike(String value) {
            addCriterion("wx_head_img_url like", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlNotLike(String value) {
            addCriterion("wx_head_img_url not like", value, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlIn(List<String> values) {
            addCriterion("wx_head_img_url in", values, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlNotIn(List<String> values) {
            addCriterion("wx_head_img_url not in", values, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlBetween(String value1, String value2) {
            addCriterion("wx_head_img_url between", value1, value2, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxHeadImgUrlNotBetween(String value1, String value2) {
            addCriterion("wx_head_img_url not between", value1, value2, "wxHeadImgUrl");
            return (Criteria) this;
        }

        public Criteria andWxLanguageIsNull() {
            addCriterion("wx_language is null");
            return (Criteria) this;
        }

        public Criteria andWxLanguageIsNotNull() {
            addCriterion("wx_language is not null");
            return (Criteria) this;
        }

        public Criteria andWxLanguageEqualTo(String value) {
            addCriterion("wx_language =", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageNotEqualTo(String value) {
            addCriterion("wx_language <>", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageGreaterThan(String value) {
            addCriterion("wx_language >", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("wx_language >=", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageLessThan(String value) {
            addCriterion("wx_language <", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageLessThanOrEqualTo(String value) {
            addCriterion("wx_language <=", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageLike(String value) {
            addCriterion("wx_language like", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageNotLike(String value) {
            addCriterion("wx_language not like", value, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageIn(List<String> values) {
            addCriterion("wx_language in", values, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageNotIn(List<String> values) {
            addCriterion("wx_language not in", values, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageBetween(String value1, String value2) {
            addCriterion("wx_language between", value1, value2, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxLanguageNotBetween(String value1, String value2) {
            addCriterion("wx_language not between", value1, value2, "wxLanguage");
            return (Criteria) this;
        }

        public Criteria andWxNickNameIsNull() {
            addCriterion("wx_nick_name is null");
            return (Criteria) this;
        }

        public Criteria andWxNickNameIsNotNull() {
            addCriterion("wx_nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andWxNickNameEqualTo(String value) {
            addCriterion("wx_nick_name =", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameNotEqualTo(String value) {
            addCriterion("wx_nick_name <>", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameGreaterThan(String value) {
            addCriterion("wx_nick_name >", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("wx_nick_name >=", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameLessThan(String value) {
            addCriterion("wx_nick_name <", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameLessThanOrEqualTo(String value) {
            addCriterion("wx_nick_name <=", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameLike(String value) {
            addCriterion("wx_nick_name like", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameNotLike(String value) {
            addCriterion("wx_nick_name not like", value, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameIn(List<String> values) {
            addCriterion("wx_nick_name in", values, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameNotIn(List<String> values) {
            addCriterion("wx_nick_name not in", values, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameBetween(String value1, String value2) {
            addCriterion("wx_nick_name between", value1, value2, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxNickNameNotBetween(String value1, String value2) {
            addCriterion("wx_nick_name not between", value1, value2, "wxNickName");
            return (Criteria) this;
        }

        public Criteria andWxProvinceIsNull() {
            addCriterion("wx_province is null");
            return (Criteria) this;
        }

        public Criteria andWxProvinceIsNotNull() {
            addCriterion("wx_province is not null");
            return (Criteria) this;
        }

        public Criteria andWxProvinceEqualTo(String value) {
            addCriterion("wx_province =", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceNotEqualTo(String value) {
            addCriterion("wx_province <>", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceGreaterThan(String value) {
            addCriterion("wx_province >", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("wx_province >=", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceLessThan(String value) {
            addCriterion("wx_province <", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceLessThanOrEqualTo(String value) {
            addCriterion("wx_province <=", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceLike(String value) {
            addCriterion("wx_province like", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceNotLike(String value) {
            addCriterion("wx_province not like", value, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceIn(List<String> values) {
            addCriterion("wx_province in", values, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceNotIn(List<String> values) {
            addCriterion("wx_province not in", values, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceBetween(String value1, String value2) {
            addCriterion("wx_province between", value1, value2, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andWxProvinceNotBetween(String value1, String value2) {
            addCriterion("wx_province not between", value1, value2, "wxProvince");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectIsNull() {
            addCriterion("credit_card_project is null");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectIsNotNull() {
            addCriterion("credit_card_project is not null");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectEqualTo(String value) {
            addCriterion("credit_card_project =", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectNotEqualTo(String value) {
            addCriterion("credit_card_project <>", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectGreaterThan(String value) {
            addCriterion("credit_card_project >", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectGreaterThanOrEqualTo(String value) {
            addCriterion("credit_card_project >=", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectLessThan(String value) {
            addCriterion("credit_card_project <", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectLessThanOrEqualTo(String value) {
            addCriterion("credit_card_project <=", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectLike(String value) {
            addCriterion("credit_card_project like", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectNotLike(String value) {
            addCriterion("credit_card_project not like", value, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectIn(List<String> values) {
            addCriterion("credit_card_project in", values, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectNotIn(List<String> values) {
            addCriterion("credit_card_project not in", values, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectBetween(String value1, String value2) {
            addCriterion("credit_card_project between", value1, value2, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andCreditCardProjectNotBetween(String value1, String value2) {
            addCriterion("credit_card_project not between", value1, value2, "creditCardProject");
            return (Criteria) this;
        }

        public Criteria andGroup13IsNull() {
            addCriterion("group13 is null");
            return (Criteria) this;
        }

        public Criteria andGroup13IsNotNull() {
            addCriterion("group13 is not null");
            return (Criteria) this;
        }

        public Criteria andGroup13EqualTo(String value) {
            addCriterion("group13 =", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13NotEqualTo(String value) {
            addCriterion("group13 <>", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13GreaterThan(String value) {
            addCriterion("group13 >", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13GreaterThanOrEqualTo(String value) {
            addCriterion("group13 >=", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13LessThan(String value) {
            addCriterion("group13 <", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13LessThanOrEqualTo(String value) {
            addCriterion("group13 <=", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13Like(String value) {
            addCriterion("group13 like", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13NotLike(String value) {
            addCriterion("group13 not like", value, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13In(List<String> values) {
            addCriterion("group13 in", values, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13NotIn(List<String> values) {
            addCriterion("group13 not in", values, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13Between(String value1, String value2) {
            addCriterion("group13 between", value1, value2, "group13");
            return (Criteria) this;
        }

        public Criteria andGroup13NotBetween(String value1, String value2) {
            addCriterion("group13 not between", value1, value2, "group13");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNull() {
            addCriterion("home_address is null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIsNotNull() {
            addCriterion("home_address is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAddressEqualTo(String value) {
            addCriterion("home_address =", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotEqualTo(String value) {
            addCriterion("home_address <>", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThan(String value) {
            addCriterion("home_address >", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("home_address >=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThan(String value) {
            addCriterion("home_address <", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("home_address <=", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressLike(String value) {
            addCriterion("home_address like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotLike(String value) {
            addCriterion("home_address not like", value, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressIn(List<String> values) {
            addCriterion("home_address in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotIn(List<String> values) {
            addCriterion("home_address not in", values, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressBetween(String value1, String value2) {
            addCriterion("home_address between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomeAddressNotBetween(String value1, String value2) {
            addCriterion("home_address not between", value1, value2, "homeAddress");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIsNull() {
            addCriterion("home_post_code is null");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIsNotNull() {
            addCriterion("home_post_code is not null");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeEqualTo(String value) {
            addCriterion("home_post_code =", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotEqualTo(String value) {
            addCriterion("home_post_code <>", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeGreaterThan(String value) {
            addCriterion("home_post_code >", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("home_post_code >=", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLessThan(String value) {
            addCriterion("home_post_code <", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLessThanOrEqualTo(String value) {
            addCriterion("home_post_code <=", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLike(String value) {
            addCriterion("home_post_code like", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotLike(String value) {
            addCriterion("home_post_code not like", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIn(List<String> values) {
            addCriterion("home_post_code in", values, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotIn(List<String> values) {
            addCriterion("home_post_code not in", values, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeBetween(String value1, String value2) {
            addCriterion("home_post_code between", value1, value2, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotBetween(String value1, String value2) {
            addCriterion("home_post_code not between", value1, value2, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateEqualTo(Date value) {
            addCriterion("last_update =", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThan(Date value) {
            addCriterion("last_update >", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThan(Date value) {
            addCriterion("last_update <", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIn(List<Date> values) {
            addCriterion("last_update in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNull() {
            addCriterion("delete_time is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNotNull() {
            addCriterion("delete_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeEqualTo(Date value) {
            addCriterion("delete_time =", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotEqualTo(Date value) {
            addCriterion("delete_time <>", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThan(Date value) {
            addCriterion("delete_time >", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("delete_time >=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThan(Date value) {
            addCriterion("delete_time <", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("delete_time <=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIn(List<Date> values) {
            addCriterion("delete_time in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotIn(List<Date> values) {
            addCriterion("delete_time not in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeBetween(Date value1, Date value2) {
            addCriterion("delete_time between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("delete_time not between", value1, value2, "deleteTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}