package com.joycity.joyclub.apifront.modal.client;

import java.util.Date;

/**
 * 直接复制api-back里的
 */
public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.birthday
     *
     * @mbg.generated
     */
    private Long birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.vip_grade
     *
     * @mbg.generated
     */
    private Integer vipGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.vip_point
     *
     * @mbg.generated
     */
    private Integer vipPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.vip_code
     *
     * @mbg.generated
     */
    private String vipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.vip_card_grade
     *
     * @mbg.generated
     */
    private String vipCardGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.edu_his
     *
     * @mbg.generated
     */
    private String eduHis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_city
     *
     * @mbg.generated
     */
    private String wxCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_country
     *
     * @mbg.generated
     */
    private String wxCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_gender
     *
     * @mbg.generated
     */
    private String wxGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_head_img_url
     *
     * @mbg.generated
     */
    private String wxHeadImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_language
     *
     * @mbg.generated
     */
    private String wxLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_nick_name
     *
     * @mbg.generated
     */
    private String wxNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wx_province
     *
     * @mbg.generated
     */
    private String wxProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.credit_card_project
     *
     * @mbg.generated
     */
    private String creditCardProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.group13
     *
     * @mbg.generated
     */
    private String group13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.home_post_code
     *
     * @mbg.generated
     */
    private String homePostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id
     *
     * @return the value of client.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id
     *
     * @param id the value for client.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.real_name
     *
     * @return the value of client.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.real_name
     *
     * @param realName the value for client.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.sex
     *
     * @return the value of client.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.sex
     *
     * @param sex the value for client.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.status
     *
     * @return the value of client.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.status
     *
     * @param status the value for client.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.tel
     *
     * @return the value of client.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.tel
     *
     * @param tel the value for client.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.type
     *
     * @return the value of client.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.type
     *
     * @param type the value for client.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.birthday
     *
     * @return the value of client.birthday
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.birthday
     *
     * @param birthday the value for client.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.vip_grade
     *
     * @return the value of client.vip_grade
     *
     * @mbg.generated
     */
    public Integer getVipGrade() {
        return vipGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.vip_grade
     *
     * @param vipGrade the value for client.vip_grade
     *
     * @mbg.generated
     */
    public void setVipGrade(Integer vipGrade) {
        this.vipGrade = vipGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.vip_point
     *
     * @return the value of client.vip_point
     *
     * @mbg.generated
     */
    public Integer getVipPoint() {
        return vipPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.vip_point
     *
     * @param vipPoint the value for client.vip_point
     *
     * @mbg.generated
     */
    public void setVipPoint(Integer vipPoint) {
        this.vipPoint = vipPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.card_no
     *
     * @return the value of client.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.card_no
     *
     * @param cardNo the value for client.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id_card
     *
     * @return the value of client.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id_card
     *
     * @param idCard the value for client.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.vip_code
     *
     * @return the value of client.vip_code
     *
     * @mbg.generated
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.vip_code
     *
     * @param vipCode the value for client.vip_code
     *
     * @mbg.generated
     */
    public void setVipCode(String vipCode) {
        this.vipCode = vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.vip_card_grade
     *
     * @return the value of client.vip_card_grade
     *
     * @mbg.generated
     */
    public String getVipCardGrade() {
        return vipCardGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.vip_card_grade
     *
     * @param vipCardGrade the value for client.vip_card_grade
     *
     * @mbg.generated
     */
    public void setVipCardGrade(String vipCardGrade) {
        this.vipCardGrade = vipCardGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.edu_his
     *
     * @return the value of client.edu_his
     *
     * @mbg.generated
     */
    public String getEduHis() {
        return eduHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.edu_his
     *
     * @param eduHis the value for client.edu_his
     *
     * @mbg.generated
     */
    public void setEduHis(String eduHis) {
        this.eduHis = eduHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_city
     *
     * @return the value of client.wx_city
     *
     * @mbg.generated
     */
    public String getWxCity() {
        return wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_city
     *
     * @param wxCity the value for client.wx_city
     *
     * @mbg.generated
     */
    public void setWxCity(String wxCity) {
        this.wxCity = wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_country
     *
     * @return the value of client.wx_country
     *
     * @mbg.generated
     */
    public String getWxCountry() {
        return wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_country
     *
     * @param wxCountry the value for client.wx_country
     *
     * @mbg.generated
     */
    public void setWxCountry(String wxCountry) {
        this.wxCountry = wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_gender
     *
     * @return the value of client.wx_gender
     *
     * @mbg.generated
     */
    public String getWxGender() {
        return wxGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_gender
     *
     * @param wxGender the value for client.wx_gender
     *
     * @mbg.generated
     */
    public void setWxGender(String wxGender) {
        this.wxGender = wxGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_head_img_url
     *
     * @return the value of client.wx_head_img_url
     *
     * @mbg.generated
     */
    public String getWxHeadImgUrl() {
        return wxHeadImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_head_img_url
     *
     * @param wxHeadImgUrl the value for client.wx_head_img_url
     *
     * @mbg.generated
     */
    public void setWxHeadImgUrl(String wxHeadImgUrl) {
        this.wxHeadImgUrl = wxHeadImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_language
     *
     * @return the value of client.wx_language
     *
     * @mbg.generated
     */
    public String getWxLanguage() {
        return wxLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_language
     *
     * @param wxLanguage the value for client.wx_language
     *
     * @mbg.generated
     */
    public void setWxLanguage(String wxLanguage) {
        this.wxLanguage = wxLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_nick_name
     *
     * @return the value of client.wx_nick_name
     *
     * @mbg.generated
     */
    public String getWxNickName() {
        return wxNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_nick_name
     *
     * @param wxNickName the value for client.wx_nick_name
     *
     * @mbg.generated
     */
    public void setWxNickName(String wxNickName) {
        this.wxNickName = wxNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wx_province
     *
     * @return the value of client.wx_province
     *
     * @mbg.generated
     */
    public String getWxProvince() {
        return wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wx_province
     *
     * @param wxProvince the value for client.wx_province
     *
     * @mbg.generated
     */
    public void setWxProvince(String wxProvince) {
        this.wxProvince = wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.credit_card_project
     *
     * @return the value of client.credit_card_project
     *
     * @mbg.generated
     */
    public String getCreditCardProject() {
        return creditCardProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.credit_card_project
     *
     * @param creditCardProject the value for client.credit_card_project
     *
     * @mbg.generated
     */
    public void setCreditCardProject(String creditCardProject) {
        this.creditCardProject = creditCardProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.group13
     *
     * @return the value of client.group13
     *
     * @mbg.generated
     */
    public String getGroup13() {
        return group13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.group13
     *
     * @param group13 the value for client.group13
     *
     * @mbg.generated
     */
    public void setGroup13(String group13) {
        this.group13 = group13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.home_address
     *
     * @return the value of client.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.home_address
     *
     * @param homeAddress the value for client.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.home_post_code
     *
     * @return the value of client.home_post_code
     *
     * @mbg.generated
     */
    public String getHomePostCode() {
        return homePostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.home_post_code
     *
     * @param homePostCode the value for client.home_post_code
     *
     * @mbg.generated
     */
    public void setHomePostCode(String homePostCode) {
        this.homePostCode = homePostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.create_time
     *
     * @return the value of client.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.create_time
     *
     * @param createTime the value for client.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.last_update
     *
     * @return the value of client.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.last_update
     *
     * @param lastUpdate the value for client.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.delete_flag
     *
     * @return the value of client.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.delete_flag
     *
     * @param deleteFlag the value for client.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.delete_time
     *
     * @return the value of client.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.delete_time
     *
     * @param deleteTime the value for client.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}