package com.joycity.joyclub.apifront.modal.project;

import java.util.Date;

/**
 * 直接复制api-back里的
 */
public class SysProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.headquarters
     *
     * @mbg.generated
     */
    private String headquarters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.vip_share
     *
     * @mbg.generated
     */
    private String vipShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.card_resource_project
     *
     * @mbg.generated
     */
    private String cardResourceProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.wechat_app_id
     *
     * @mbg.generated
     */
    private String wechatAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.wechat_app_secret
     *
     * @mbg.generated
     */
    private String wechatAppSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.wechat_token_address
     *
     * @mbg.generated
     */
    private String wechatTokenAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.id
     *
     * @return the value of sys_project.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.id
     *
     * @param id the value for sys_project.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.type
     *
     * @return the value of sys_project.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.type
     *
     * @param type the value for sys_project.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.name
     *
     * @return the value of sys_project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.name
     *
     * @param name the value for sys_project.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.headquarters
     *
     * @return the value of sys_project.headquarters
     *
     * @mbg.generated
     */
    public String getHeadquarters() {
        return headquarters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.headquarters
     *
     * @param headquarters the value for sys_project.headquarters
     *
     * @mbg.generated
     */
    public void setHeadquarters(String headquarters) {
        this.headquarters = headquarters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.code
     *
     * @return the value of sys_project.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.code
     *
     * @param code the value for sys_project.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.vip_share
     *
     * @return the value of sys_project.vip_share
     *
     * @mbg.generated
     */
    public String getVipShare() {
        return vipShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.vip_share
     *
     * @param vipShare the value for sys_project.vip_share
     *
     * @mbg.generated
     */
    public void setVipShare(String vipShare) {
        this.vipShare = vipShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.card_resource_project
     *
     * @return the value of sys_project.card_resource_project
     *
     * @mbg.generated
     */
    public String getCardResourceProject() {
        return cardResourceProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.card_resource_project
     *
     * @param cardResourceProject the value for sys_project.card_resource_project
     *
     * @mbg.generated
     */
    public void setCardResourceProject(String cardResourceProject) {
        this.cardResourceProject = cardResourceProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.address
     *
     * @return the value of sys_project.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.address
     *
     * @param address the value for sys_project.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.remark
     *
     * @return the value of sys_project.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.remark
     *
     * @param remark the value for sys_project.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.contact_name
     *
     * @return the value of sys_project.contact_name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.contact_name
     *
     * @param contactName the value for sys_project.contact_name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.contact_phone
     *
     * @return the value of sys_project.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.contact_phone
     *
     * @param contactPhone the value for sys_project.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.wechat_app_id
     *
     * @return the value of sys_project.wechat_app_id
     *
     * @mbg.generated
     */
    public String getWechatAppId() {
        return wechatAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.wechat_app_id
     *
     * @param wechatAppId the value for sys_project.wechat_app_id
     *
     * @mbg.generated
     */
    public void setWechatAppId(String wechatAppId) {
        this.wechatAppId = wechatAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.wechat_app_secret
     *
     * @return the value of sys_project.wechat_app_secret
     *
     * @mbg.generated
     */
    public String getWechatAppSecret() {
        return wechatAppSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.wechat_app_secret
     *
     * @param wechatAppSecret the value for sys_project.wechat_app_secret
     *
     * @mbg.generated
     */
    public void setWechatAppSecret(String wechatAppSecret) {
        this.wechatAppSecret = wechatAppSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.wechat_token_address
     *
     * @return the value of sys_project.wechat_token_address
     *
     * @mbg.generated
     */
    public String getWechatTokenAddress() {
        return wechatTokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.wechat_token_address
     *
     * @param wechatTokenAddress the value for sys_project.wechat_token_address
     *
     * @mbg.generated
     */
    public void setWechatTokenAddress(String wechatTokenAddress) {
        this.wechatTokenAddress = wechatTokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.create_time
     *
     * @return the value of sys_project.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.create_time
     *
     * @param createTime the value for sys_project.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.last_update
     *
     * @return the value of sys_project.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.last_update
     *
     * @param lastUpdate the value for sys_project.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.delete_flag
     *
     * @return the value of sys_project.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.delete_flag
     *
     * @param deleteFlag the value for sys_project.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.delete_time
     *
     * @return the value of sys_project.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.delete_time
     *
     * @param deleteTime the value for sys_project.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}