package com.joycity.joyclub.apifront.modal.project;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public SysProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andHeadquartersIsNull() {
            addCriterion("headquarters is null");
            return (Criteria) this;
        }

        public Criteria andHeadquartersIsNotNull() {
            addCriterion("headquarters is not null");
            return (Criteria) this;
        }

        public Criteria andHeadquartersEqualTo(String value) {
            addCriterion("headquarters =", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersNotEqualTo(String value) {
            addCriterion("headquarters <>", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersGreaterThan(String value) {
            addCriterion("headquarters >", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersGreaterThanOrEqualTo(String value) {
            addCriterion("headquarters >=", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersLessThan(String value) {
            addCriterion("headquarters <", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersLessThanOrEqualTo(String value) {
            addCriterion("headquarters <=", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersLike(String value) {
            addCriterion("headquarters like", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersNotLike(String value) {
            addCriterion("headquarters not like", value, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersIn(List<String> values) {
            addCriterion("headquarters in", values, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersNotIn(List<String> values) {
            addCriterion("headquarters not in", values, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersBetween(String value1, String value2) {
            addCriterion("headquarters between", value1, value2, "headquarters");
            return (Criteria) this;
        }

        public Criteria andHeadquartersNotBetween(String value1, String value2) {
            addCriterion("headquarters not between", value1, value2, "headquarters");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andVipShareIsNull() {
            addCriterion("vip_share is null");
            return (Criteria) this;
        }

        public Criteria andVipShareIsNotNull() {
            addCriterion("vip_share is not null");
            return (Criteria) this;
        }

        public Criteria andVipShareEqualTo(String value) {
            addCriterion("vip_share =", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareNotEqualTo(String value) {
            addCriterion("vip_share <>", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareGreaterThan(String value) {
            addCriterion("vip_share >", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareGreaterThanOrEqualTo(String value) {
            addCriterion("vip_share >=", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareLessThan(String value) {
            addCriterion("vip_share <", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareLessThanOrEqualTo(String value) {
            addCriterion("vip_share <=", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareLike(String value) {
            addCriterion("vip_share like", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareNotLike(String value) {
            addCriterion("vip_share not like", value, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareIn(List<String> values) {
            addCriterion("vip_share in", values, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareNotIn(List<String> values) {
            addCriterion("vip_share not in", values, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareBetween(String value1, String value2) {
            addCriterion("vip_share between", value1, value2, "vipShare");
            return (Criteria) this;
        }

        public Criteria andVipShareNotBetween(String value1, String value2) {
            addCriterion("vip_share not between", value1, value2, "vipShare");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectIsNull() {
            addCriterion("card_resource_project is null");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectIsNotNull() {
            addCriterion("card_resource_project is not null");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectEqualTo(String value) {
            addCriterion("card_resource_project =", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectNotEqualTo(String value) {
            addCriterion("card_resource_project <>", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectGreaterThan(String value) {
            addCriterion("card_resource_project >", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectGreaterThanOrEqualTo(String value) {
            addCriterion("card_resource_project >=", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectLessThan(String value) {
            addCriterion("card_resource_project <", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectLessThanOrEqualTo(String value) {
            addCriterion("card_resource_project <=", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectLike(String value) {
            addCriterion("card_resource_project like", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectNotLike(String value) {
            addCriterion("card_resource_project not like", value, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectIn(List<String> values) {
            addCriterion("card_resource_project in", values, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectNotIn(List<String> values) {
            addCriterion("card_resource_project not in", values, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectBetween(String value1, String value2) {
            addCriterion("card_resource_project between", value1, value2, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andCardResourceProjectNotBetween(String value1, String value2) {
            addCriterion("card_resource_project not between", value1, value2, "cardResourceProject");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNull() {
            addCriterion("contact_name is null");
            return (Criteria) this;
        }

        public Criteria andContactNameIsNotNull() {
            addCriterion("contact_name is not null");
            return (Criteria) this;
        }

        public Criteria andContactNameEqualTo(String value) {
            addCriterion("contact_name =", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotEqualTo(String value) {
            addCriterion("contact_name <>", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThan(String value) {
            addCriterion("contact_name >", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameGreaterThanOrEqualTo(String value) {
            addCriterion("contact_name >=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThan(String value) {
            addCriterion("contact_name <", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLessThanOrEqualTo(String value) {
            addCriterion("contact_name <=", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameLike(String value) {
            addCriterion("contact_name like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotLike(String value) {
            addCriterion("contact_name not like", value, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameIn(List<String> values) {
            addCriterion("contact_name in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotIn(List<String> values) {
            addCriterion("contact_name not in", values, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameBetween(String value1, String value2) {
            addCriterion("contact_name between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactNameNotBetween(String value1, String value2) {
            addCriterion("contact_name not between", value1, value2, "contactName");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("contact_phone like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdIsNull() {
            addCriterion("wechat_app_id is null");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdIsNotNull() {
            addCriterion("wechat_app_id is not null");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdEqualTo(String value) {
            addCriterion("wechat_app_id =", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdNotEqualTo(String value) {
            addCriterion("wechat_app_id <>", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdGreaterThan(String value) {
            addCriterion("wechat_app_id >", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_app_id >=", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdLessThan(String value) {
            addCriterion("wechat_app_id <", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdLessThanOrEqualTo(String value) {
            addCriterion("wechat_app_id <=", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdLike(String value) {
            addCriterion("wechat_app_id like", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdNotLike(String value) {
            addCriterion("wechat_app_id not like", value, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdIn(List<String> values) {
            addCriterion("wechat_app_id in", values, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdNotIn(List<String> values) {
            addCriterion("wechat_app_id not in", values, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdBetween(String value1, String value2) {
            addCriterion("wechat_app_id between", value1, value2, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppIdNotBetween(String value1, String value2) {
            addCriterion("wechat_app_id not between", value1, value2, "wechatAppId");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretIsNull() {
            addCriterion("wechat_app_secret is null");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretIsNotNull() {
            addCriterion("wechat_app_secret is not null");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretEqualTo(String value) {
            addCriterion("wechat_app_secret =", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretNotEqualTo(String value) {
            addCriterion("wechat_app_secret <>", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretGreaterThan(String value) {
            addCriterion("wechat_app_secret >", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_app_secret >=", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretLessThan(String value) {
            addCriterion("wechat_app_secret <", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretLessThanOrEqualTo(String value) {
            addCriterion("wechat_app_secret <=", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretLike(String value) {
            addCriterion("wechat_app_secret like", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretNotLike(String value) {
            addCriterion("wechat_app_secret not like", value, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretIn(List<String> values) {
            addCriterion("wechat_app_secret in", values, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretNotIn(List<String> values) {
            addCriterion("wechat_app_secret not in", values, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretBetween(String value1, String value2) {
            addCriterion("wechat_app_secret between", value1, value2, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatAppSecretNotBetween(String value1, String value2) {
            addCriterion("wechat_app_secret not between", value1, value2, "wechatAppSecret");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressIsNull() {
            addCriterion("wechat_token_address is null");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressIsNotNull() {
            addCriterion("wechat_token_address is not null");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressEqualTo(String value) {
            addCriterion("wechat_token_address =", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressNotEqualTo(String value) {
            addCriterion("wechat_token_address <>", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressGreaterThan(String value) {
            addCriterion("wechat_token_address >", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_token_address >=", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressLessThan(String value) {
            addCriterion("wechat_token_address <", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressLessThanOrEqualTo(String value) {
            addCriterion("wechat_token_address <=", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressLike(String value) {
            addCriterion("wechat_token_address like", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressNotLike(String value) {
            addCriterion("wechat_token_address not like", value, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressIn(List<String> values) {
            addCriterion("wechat_token_address in", values, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressNotIn(List<String> values) {
            addCriterion("wechat_token_address not in", values, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressBetween(String value1, String value2) {
            addCriterion("wechat_token_address between", value1, value2, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andWechatTokenAddressNotBetween(String value1, String value2) {
            addCriterion("wechat_token_address not between", value1, value2, "wechatTokenAddress");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateEqualTo(Date value) {
            addCriterion("last_update =", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThan(Date value) {
            addCriterion("last_update >", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThan(Date value) {
            addCriterion("last_update <", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateIn(List<Date> values) {
            addCriterion("last_update in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "lastUpdate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNull() {
            addCriterion("delete_time is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNotNull() {
            addCriterion("delete_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeEqualTo(Date value) {
            addCriterion("delete_time =", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotEqualTo(Date value) {
            addCriterion("delete_time <>", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThan(Date value) {
            addCriterion("delete_time >", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("delete_time >=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThan(Date value) {
            addCriterion("delete_time <", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("delete_time <=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIn(List<Date> values) {
            addCriterion("delete_time in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotIn(List<Date> values) {
            addCriterion("delete_time not in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeBetween(Date value1, Date value2) {
            addCriterion("delete_time between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("delete_time not between", value1, value2, "deleteTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_project
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_project
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}