package com.joycity.joyclub.apifront.modal.product;

import java.util.Date;

public class Product {
    private String htmlContent;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.store_id
     *
     * @mbg.generated
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.designer_id
     *
     * @mbg.generated
     */
    private Long designerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.display_weight
     *
     * @mbg.generated
     */
    private Integer displayWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.base_price
     *
     * @mbg.generated
     */
    private Integer basePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.portrait
     *
     * @mbg.generated
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.carousel
     *
     * @mbg.generated
     */
    private String carousel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.id
     *
     * @return the value of sale_product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.id
     *
     * @param id the value for sale_product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.store_id
     *
     * @return the value of sale_product.store_id
     *
     * @mbg.generated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.store_id
     *
     * @param storeId the value for sale_product.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.category_id
     *
     * @return the value of sale_product.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.category_id
     *
     * @param categoryId the value for sale_product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.designer_id
     *
     * @return the value of sale_product.designer_id
     *
     * @mbg.generated
     */
    public Long getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.designer_id
     *
     * @param designerId the value for sale_product.designer_id
     *
     * @mbg.generated
     */
    public void setDesignerId(Long designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.name
     *
     * @return the value of sale_product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.name
     *
     * @param name the value for sale_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.display_weight
     *
     * @return the value of sale_product.display_weight
     *
     * @mbg.generated
     */
    public Integer getDisplayWeight() {
        return displayWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.display_weight
     *
     * @param displayWeight the value for sale_product.display_weight
     *
     * @mbg.generated
     */
    public void setDisplayWeight(Integer displayWeight) {
        this.displayWeight = displayWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.base_price
     *
     * @return the value of sale_product.base_price
     *
     * @mbg.generated
     */
    public Integer getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.base_price
     *
     * @param basePrice the value for sale_product.base_price
     *
     * @mbg.generated
     */
    public void setBasePrice(Integer basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.portrait
     *
     * @return the value of sale_product.portrait
     *
     * @mbg.generated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.portrait
     *
     * @param portrait the value for sale_product.portrait
     *
     * @mbg.generated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.carousel
     *
     * @return the value of sale_product.carousel
     *
     * @mbg.generated
     */
    public String getCarousel() {
        return carousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.carousel
     *
     * @param carousel the value for sale_product.carousel
     *
     * @mbg.generated
     */
    public void setCarousel(String carousel) {
        this.carousel = carousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.create_time
     *
     * @return the value of sale_product.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.create_time
     *
     * @param createTime the value for sale_product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.last_update
     *
     * @return the value of sale_product.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.last_update
     *
     * @param lastUpdate the value for sale_product.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.delete_flag
     *
     * @return the value of sale_product.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.delete_flag
     *
     * @param deleteFlag the value for sale_product.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product.delete_time
     *
     * @return the value of sale_product.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product.delete_time
     *
     * @param deleteTime the value for sale_product.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    public String getHtmlContent() {
        return htmlContent;
    }

    public void setHtmlContent(String htmlContent) {
        this.htmlContent = htmlContent;
    }
}