package com.joycity.joyclub.apifront.modal.order;

import java.util.Date;

public class ProductOrderStore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.store_id
     *
     * @mbg.generated
     */
    private Long storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.money_sum
     *
     * @mbg.generated
     */
    private Integer moneySum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.point_sum
     *
     * @mbg.generated
     */
    private Integer pointSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.delivery_time
     *
     * @mbg.generated
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.delivery_code
     *
     * @mbg.generated
     */
    private String deliveryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.receive_time
     *
     * @mbg.generated
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.notice_refund_time
     *
     * @mbg.generated
     */
    private Date noticeRefundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.refund_time
     *
     * @mbg.generated
     */
    private Date refundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order_store.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.id
     *
     * @return the value of sale_product_order_store.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.id
     *
     * @param id the value for sale_product_order_store.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.order_id
     *
     * @return the value of sale_product_order_store.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.order_id
     *
     * @param orderId the value for sale_product_order_store.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.store_id
     *
     * @return the value of sale_product_order_store.store_id
     *
     * @mbg.generated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.store_id
     *
     * @param storeId the value for sale_product_order_store.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.money_sum
     *
     * @return the value of sale_product_order_store.money_sum
     *
     * @mbg.generated
     */
    public Integer getMoneySum() {
        return moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.money_sum
     *
     * @param moneySum the value for sale_product_order_store.money_sum
     *
     * @mbg.generated
     */
    public void setMoneySum(Integer moneySum) {
        this.moneySum = moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.point_sum
     *
     * @return the value of sale_product_order_store.point_sum
     *
     * @mbg.generated
     */
    public Integer getPointSum() {
        return pointSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.point_sum
     *
     * @param pointSum the value for sale_product_order_store.point_sum
     *
     * @mbg.generated
     */
    public void setPointSum(Integer pointSum) {
        this.pointSum = pointSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.status
     *
     * @return the value of sale_product_order_store.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.status
     *
     * @param status the value for sale_product_order_store.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.delivery_time
     *
     * @return the value of sale_product_order_store.delivery_time
     *
     * @mbg.generated
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.delivery_time
     *
     * @param deliveryTime the value for sale_product_order_store.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.delivery_company
     *
     * @return the value of sale_product_order_store.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.delivery_company
     *
     * @param deliveryCompany the value for sale_product_order_store.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.delivery_code
     *
     * @return the value of sale_product_order_store.delivery_code
     *
     * @mbg.generated
     */
    public String getDeliveryCode() {
        return deliveryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.delivery_code
     *
     * @param deliveryCode the value for sale_product_order_store.delivery_code
     *
     * @mbg.generated
     */
    public void setDeliveryCode(String deliveryCode) {
        this.deliveryCode = deliveryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.receive_time
     *
     * @return the value of sale_product_order_store.receive_time
     *
     * @mbg.generated
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.receive_time
     *
     * @param receiveTime the value for sale_product_order_store.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.notice_refund_time
     *
     * @return the value of sale_product_order_store.notice_refund_time
     *
     * @mbg.generated
     */
    public Date getNoticeRefundTime() {
        return noticeRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.notice_refund_time
     *
     * @param noticeRefundTime the value for sale_product_order_store.notice_refund_time
     *
     * @mbg.generated
     */
    public void setNoticeRefundTime(Date noticeRefundTime) {
        this.noticeRefundTime = noticeRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.refund_time
     *
     * @return the value of sale_product_order_store.refund_time
     *
     * @mbg.generated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.refund_time
     *
     * @param refundTime the value for sale_product_order_store.refund_time
     *
     * @mbg.generated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.create_time
     *
     * @return the value of sale_product_order_store.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.create_time
     *
     * @param createTime the value for sale_product_order_store.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.last_update
     *
     * @return the value of sale_product_order_store.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.last_update
     *
     * @param lastUpdate the value for sale_product_order_store.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.delete_flag
     *
     * @return the value of sale_product_order_store.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.delete_flag
     *
     * @param deleteFlag the value for sale_product_order_store.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order_store.delete_time
     *
     * @return the value of sale_product_order_store.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order_store.delete_time
     *
     * @param deleteTime the value for sale_product_order_store.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}