package com.joycity.joyclub.apiback.modal.order;

import java.util.Date;

public class ProductOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.out_pay_code
     *
     * @mbg.generated
     */
    private String outPayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.client_id
     *
     * @mbg.generated
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.receive_type
     *
     * @mbg.generated
     */
    private Byte receiveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.money_sum
     *
     * @mbg.generated
     */
    private Integer moneySum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.point_sum
     *
     * @mbg.generated
     */
    private Integer pointSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.pay_type
     *
     * @mbg.generated
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.cancel_time
     *
     * @mbg.generated
     */
    private Date cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.canceler
     *
     * @mbg.generated
     */
    private Byte canceler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.receiver_phone
     *
     * @mbg.generated
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.receiver_postcode
     *
     * @mbg.generated
     */
    private String receiverPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_product_order.delete_time
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.id
     *
     * @return the value of sale_product_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.id
     *
     * @param id the value for sale_product_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.code
     *
     * @return the value of sale_product_order.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.code
     *
     * @param code the value for sale_product_order.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.out_pay_code
     *
     * @return the value of sale_product_order.out_pay_code
     *
     * @mbg.generated
     */
    public String getOutPayCode() {
        return outPayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.out_pay_code
     *
     * @param outPayCode the value for sale_product_order.out_pay_code
     *
     * @mbg.generated
     */
    public void setOutPayCode(String outPayCode) {
        this.outPayCode = outPayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.project_id
     *
     * @return the value of sale_product_order.project_id
     *
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.project_id
     *
     * @param projectId the value for sale_product_order.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.client_id
     *
     * @return the value of sale_product_order.client_id
     *
     * @mbg.generated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.client_id
     *
     * @param clientId the value for sale_product_order.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.receive_type
     *
     * @return the value of sale_product_order.receive_type
     *
     * @mbg.generated
     */
    public Byte getReceiveType() {
        return receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.receive_type
     *
     * @param receiveType the value for sale_product_order.receive_type
     *
     * @mbg.generated
     */
    public void setReceiveType(Byte receiveType) {
        this.receiveType = receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.status
     *
     * @return the value of sale_product_order.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.status
     *
     * @param status the value for sale_product_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.money_sum
     *
     * @return the value of sale_product_order.money_sum
     *
     * @mbg.generated
     */
    public Integer getMoneySum() {
        return moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.money_sum
     *
     * @param moneySum the value for sale_product_order.money_sum
     *
     * @mbg.generated
     */
    public void setMoneySum(Integer moneySum) {
        this.moneySum = moneySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.point_sum
     *
     * @return the value of sale_product_order.point_sum
     *
     * @mbg.generated
     */
    public Integer getPointSum() {
        return pointSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.point_sum
     *
     * @param pointSum the value for sale_product_order.point_sum
     *
     * @mbg.generated
     */
    public void setPointSum(Integer pointSum) {
        this.pointSum = pointSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.pay_type
     *
     * @return the value of sale_product_order.pay_type
     *
     * @mbg.generated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.pay_type
     *
     * @param payType the value for sale_product_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.pay_time
     *
     * @return the value of sale_product_order.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.pay_time
     *
     * @param payTime the value for sale_product_order.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.cancel_time
     *
     * @return the value of sale_product_order.cancel_time
     *
     * @mbg.generated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.cancel_time
     *
     * @param cancelTime the value for sale_product_order.cancel_time
     *
     * @mbg.generated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.canceler
     *
     * @return the value of sale_product_order.canceler
     *
     * @mbg.generated
     */
    public Byte getCanceler() {
        return canceler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.canceler
     *
     * @param canceler the value for sale_product_order.canceler
     *
     * @mbg.generated
     */
    public void setCanceler(Byte canceler) {
        this.canceler = canceler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.receiver_name
     *
     * @return the value of sale_product_order.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.receiver_name
     *
     * @param receiverName the value for sale_product_order.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.receiver_phone
     *
     * @return the value of sale_product_order.receiver_phone
     *
     * @mbg.generated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.receiver_phone
     *
     * @param receiverPhone the value for sale_product_order.receiver_phone
     *
     * @mbg.generated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.receiver_address
     *
     * @return the value of sale_product_order.receiver_address
     *
     * @mbg.generated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.receiver_address
     *
     * @param receiverAddress the value for sale_product_order.receiver_address
     *
     * @mbg.generated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.receiver_postcode
     *
     * @return the value of sale_product_order.receiver_postcode
     *
     * @mbg.generated
     */
    public String getReceiverPostcode() {
        return receiverPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.receiver_postcode
     *
     * @param receiverPostcode the value for sale_product_order.receiver_postcode
     *
     * @mbg.generated
     */
    public void setReceiverPostcode(String receiverPostcode) {
        this.receiverPostcode = receiverPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.create_time
     *
     * @return the value of sale_product_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.create_time
     *
     * @param createTime the value for sale_product_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.last_update
     *
     * @return the value of sale_product_order.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.last_update
     *
     * @param lastUpdate the value for sale_product_order.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.delete_flag
     *
     * @return the value of sale_product_order.delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.delete_flag
     *
     * @param deleteFlag the value for sale_product_order.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_product_order.delete_time
     *
     * @return the value of sale_product_order.delete_time
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_product_order.delete_time
     *
     * @param deleteTime the value for sale_product_order.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}